// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClcZvn7efjIL-0-pVoFPU4hTnkotLPmrY',
    appId: '1:743082677389:web:d80e25b86a060b1accbec4',
    messagingSenderId: '743082677389',
    projectId: 'dayone-33805',
    authDomain: 'dayone-33805.firebaseapp.com',
    storageBucket: 'dayone-33805.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCN92yuLPjqNKNpbuSqM0J_SC4ITYQ_dM',
    appId: '1:743082677389:android:4ffa739a191bdc5eccbec4',
    messagingSenderId: '743082677389',
    projectId: 'dayone-33805',
    storageBucket: 'dayone-33805.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBog9Lgt0cbCmYve9e4zA0u-4v2tHIfU7I',
    appId: '1:743082677389:ios:7382a68e4d002ec9ccbec4',
    messagingSenderId: '743082677389',
    projectId: 'dayone-33805',
    storageBucket: 'dayone-33805.appspot.com',
    androidClientId: '743082677389-fhlttd8l0olruonv8pntegs4c0n0q0dh.apps.googleusercontent.com',
    iosClientId: '743082677389-omesk5bkpo2ro03r1j4nvlgcoffc9kif.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTemplate',
  );
}
